config/routes.rb
Store::Application.routes.draw do
  resources :products do
    collection { post :import }
  end
  root to: 'products#index'
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :cant1, :cant2, :cantidad, :cliente, :fecha, :guia, :igv, :importe, :moneda, :numero, :preciocigv, :preciosigv, :ruc, :serie, :td, :vventa



def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
  
  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      product = find_by_id(row["id"]) || new
      product.attributes = row.to_hash.slice(*accessible_attributes)
      product.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    
    when ".csv" then Csv.new(file.path, nil, :ignore)
    when ".xls" then Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  

  
 def index
  ##  @products = Product.order(:numero)

    @products = Product.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html
      format.csv { send_data @products.to_csv }
      format.xls # { send_data @products.to_csv(col_sep: "\t") }
    end

  end
  
  def import
    Product.import(params[:file])
    redirect_to root_url, notice: "Facturas importadas."
  end
  
  def new
  end

  def create
  end

  def show
    @product = Product.find(params[:id]);
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def enviar 
      redirect_to root_url, notice: "Facturas importadas."
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1>Facturas</h1>
<p>
  Download:
  <%= link_to "CSV", products_path(format: "csv") %> |
  <%= link_to "Excel", products_path(format: "xls") %>
</p>

<table id="Enviar Facturas a Sunat ">
  <tr>
    <th>Fecha</th>    
    <th>serie</th>
    <th>Numero</th>
    <th>Ruc</th>
    <th>Cantidad</th>    
    <th>Pre.S/Igv</th>
    <th>Pre.C/Igv</th>
    <th>V.Venta</th>
    <th>IGV</th>
    <th>Importe</th>
    <th>Guia</th>
  </tr>
  
<% @products.each do |product| %>
  <tr>
    <td><%= product.fecha.strftime("%d/%m/%y") %></td>
    <td><%= product.serie.strip %></td>
    <td><%= product.numero.strip %></td>  
    <td><%= product.ruc   %></td>  
    <td><%= product.cant1 %></td>    
    <td><%= number_to_currency(product.preciosigv , :unit => "S/. ")  %></td>
    <td><%= number_to_currency(product.preciocigv, :unit => "S/. ")  %></td>
    <td><%= number_to_currency(product.vventa, :unit => "") %></td>
    <td><%= number_to_currency(product.igv, :unit => "") %></td>
    <td><%= number_to_currency(product.importe, :unit => "") %></td>
    <td><%= product.guia  %></td> 
    <td><%= link_to "Ver", product %> </td> 

  </tr>
<% end %>
</table>

<h2>Importar Archivo Facturas "*.csv"</h2>

<%= form_tag import_products_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Importar " %>
<% end %>
<p> 

</p>

<%= will_paginate @products %>

app/views/products/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">ID</Data></Cell>
        <Cell><Data ss:Type="String">Name</Data></Cell>
        <Cell><Data ss:Type="String">Release Date</Data></Cell>
        <Cell><Data ss:Type="String">Price</Data></Cell>
      </Row>
    <% @products.each do |product| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= product.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= product.released_on %></Data></Cell>
        <Cell><Data ss:Type="Number"><%= product.price %></Data></Cell>
      </Row>
    <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/products/show.html.erb
<h1> Visualizar Factura</h1>

<p>      </p>

<h2> Número : <%= @product.serie %> - <%= @product.numero %>  </h2>

<div>
 <h4>  Fecha        : <%= @product.fecha %></h4>
 <h4>  Ruc          : <%= @product.ruc   %></h4>
 <h4>  Cantidad     : <%= @product.cant1 %></h4>
 <h4>  Precio S.Igv : <%= (@product.preciosigv)  %></h4>
 <h4>  Precio C.Igv : <%= number_to_currency(@product.preciocigv, :unit => "S/. ")  %></h4>
 <h4>  V.Venta      : <%= number_to_currency(@product.vventa, :unit => "S/. ") %></h4>
 <h4>  I.G.V.       : <%= number_to_currency(@product.igv, :unit => "S/. ") %></h4>
 <h4>  Importe      : <%= number_to_currency(@product.importe, :unit => "S/. ") %></h4>
 <h4>  Guia         : <%= @product.guia %></h4> 

</div>


<%= form_tag import_products_path, multipart: true do %>
  <%= submit_tag "Enviar Sunat " %>
<% end %>

<p> <%= link_to "Volver", products_path %> </p>